name: Compile and Run C Programs

on:
  push:
    paths:
      - '**.c'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt-get install build-essential

    - name: Find and Compile all C files
      run: |
        mkdir -p bin
        for file in $(find . -name "*.c"); do
          exe_name=$(basename "$file" .c)
          gcc "$file" -o "bin/$exe_name" || exit 1
        done

    - name: Run all compiled programs
      run: |
        for exe in bin/*; do
          echo "Running $exe:"
          "$exe"
          echo "------"
        done
