name: Compile and Run C Programs

on:
  push:
    paths:
      - '**.c'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt-get install -y build-essential

    - name: Compile only files with 'int main'
      run: |
        mkdir -p bin
        echo "Compiling C files with 'int main' only..."
        for file in $(find . -name "*.c"); do
          if grep -q "int main" "$file"; then
            exe_name=$(basename "$file" .c)
            echo "✅ Compiling $file -> bin/$exe_name"
            gcc "$file" -o "bin/$exe_name" || exit 1
          else
            echo "⚠️ Skipping $file (no 'int main')"
          fi
        done

    - name: Run compiled programs
      run: |
        echo "Running executables in bin/:"
        for exe in bin/*; do
          echo "===================="
          echo "Running $exe"
          "$exe" || echo "❌ Error running $exe"
          echo
        done
