name: Compile and Run C Programs

on:
  push:
    paths:
      - '**.c'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt-get install -y build-essential

    - name: Compile only files with main()
      run: |
        set -x  # Debug output

        mkdir -p bin

        echo "Compiling only C files that contain a 'main' function"

        for file in $(find . -name "*.c"); do
          # Check if file contains a main function (ignoring spaces, tabs)
          if grep -qP '\b(main)\s*\(' "$file"; then
            exe_name=$(basename "$file" .c)
            echo "✅ Compiling $file -> bin/$exe_name"
            gcc "$file" -o "bin/$exe_name" 2> gcc_errors.log || echo "❌ Compilation failed for $file"
          else
            echo "⚠️ Skipping $file (no main function)"
          fi
        done

    - name: Run compiled programs
      run: |
        echo "Running executables in bin/:"
        for exe in bin/*; do
          echo "===================="
          echo "Running $exe"
          "$exe" || echo "❌ Error running $exe"
          echo
        done
