name: Compile and Run C Programs (With main())

on:
  push:
    paths:
      - '**.c'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt-get install -y build-essential

    - name: Compile and Run Programs with int main()
      run: |
        mkdir -p bin
        for file in $(find . -name "*.c"); do
          if grep -qE "int[[:space:]]+main[[:space:]]*\(" "$file"; then
            exe_name=$(basename "$file" .c)
            echo "✅ Compiling $file..."
            gcc "$file" -o "bin/$exe_name" && ./bin/$exe_name
          else
            echo "⚠️ Skipping $file: no valid 'int main()' found."
          fi
        done
